### PR TITLE
Don't make symbols from character vector

### LINKED ISSUE #7: Wrap variables in one_of() in quotes
## The problem

The vars that go in the `one_of()` selector should perhaps be quoted. Currently, if a user copies and pastes the code they will get: `Error: object '{var_name}' not found` 

## Reproducible example

``` r
library(dplyr)
library(ggplot2)
library(recipes)

usemodels::use_glmnet(cty ~ ., data = mpg)
#> glmnet_recipe <- 
#>   recipe(formula = cty ~ ., data = mpg) %>% 
#>   step_string2factor(one_of(manufacturer, model, trans, drv, fl, class)) %>% 
#>   step_novel(all_nominal(), -all_outcomes()) %>% 
#>   step_dummy(all_nominal(), -all_outcomes()) %>% 
#>   step_zv(all_predictors()) %>% 
#>   step_normalize(all_predictors(), -all_nominal()) 
#> 
#> glmnet_spec <- 
#>   linear_reg(penalty = tune(), mixture = tune()) %>% 
#>   set_mode("regression") %>% 
#>   set_engine("glmnet") 
#> 
#> glmnet_workflow <- 
#>   workflow() %>% 
#>   add_recipe(glmnet_recipe) %>% 
#>   add_model(glmnet_spec) 
#> 
#> glmnet_grid <- tidyr::crossing(penalty = 10^seq(-6, -1, length.out = 20), mixture = c(0.05, 
#>     0.2, 0.4, 0.6, 0.8, 1)) 
#> 
#> glmnet_tune <- 
#>   tune_grid(glmnet_workflow, resamples = stop("add your rsample object"), grid = glmnet_grid)

glmnet_recipe <- 
  recipe(formula = cty ~ ., data = mpg) %>% 
  step_string2factor(one_of(manufacturer, model, trans, drv, fl, class)) %>% 
  step_novel(all_nominal(), -all_outcomes()) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors(), -all_nominal()) 

prep(glmnet_recipe, mpg) %>% juice()
#> Error: object 'manufacturer' not found

devtools::session_info()
#> Warning in system("timedatectl", intern = TRUE): running command 'timedatectl'
#> had status 1
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Ubuntu 16.04.6 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  C.UTF-8                     
#>  ctype    C.UTF-8                     
#>  tz       Etc/UTC                     
#>  date     2020-10-12                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source        
#>  assertthat    0.2.1      2019-03-21 [1] RSPM (R 4.0.2)
#>  backports     1.1.10     2020-09-15 [1] RSPM (R 4.0.2)
#>  callr         3.4.4      2020-09-07 [1] RSPM (R 4.0.2)
#>  class         7.3-17     2020-04-26 [2] CRAN (R 4.0.2)
#>  cli           2.0.2      2020-02-28 [1] RSPM (R 4.0.2)
#>  codetools     0.2-16     2018-12-24 [2] CRAN (R 4.0.2)
#>  colorspace    1.4-1      2019-03-18 [1] RSPM (R 4.0.2)
#>  crayon        1.3.4      2017-09-16 [1] RSPM (R 4.0.2)
#>  desc          1.2.0      2018-05-01 [1] RSPM (R 4.0.2)
#>  devtools      2.3.2      2020-09-18 [1] RSPM (R 4.0.2)
#>  dials         0.0.9      2020-09-16 [1] RSPM (R 4.0.2)
#>  DiceDesign    1.8-1      2019-07-31 [1] RSPM (R 4.0.2)
#>  digest        0.6.25     2020-02-23 [1] RSPM (R 4.0.2)
#>  dplyr       * 1.0.2      2020-08-18 [1] RSPM (R 4.0.2)
#>  ellipsis      0.3.1      2020-05-15 [1] RSPM (R 4.0.2)
#>  evaluate      0.14       2019-05-28 [1] RSPM (R 4.0.2)
#>  fansi         0.4.1      2020-01-08 [1] RSPM (R 4.0.2)
#>  foreach       1.5.0      2020-03-30 [1] RSPM (R 4.0.2)
#>  fs            1.5.0      2020-07-31 [1] RSPM (R 4.0.2)
#>  generics      0.0.2      2018-11-29 [1] RSPM (R 4.0.2)
#>  ggplot2     * 3.3.2      2020-06-19 [1] RSPM (R 4.0.2)
#>  glue          1.4.2      2020-08-27 [1] RSPM (R 4.0.2)
#>  gower         0.2.2      2020-06-23 [1] RSPM (R 4.0.2)
#>  GPfit         1.0-8      2019-02-08 [1] RSPM (R 4.0.2)
#>  gtable        0.3.0      2019-03-25 [1] RSPM (R 4.0.2)
#>  highr         0.8        2019-03-20 [1] RSPM (R 4.0.2)
#>  htmltools     0.5.0      2020-06-16 [1] RSPM (R 4.0.2)
#>  ipred         0.9-9      2019-04-28 [1] RSPM (R 4.0.2)
#>  iterators     1.0.12     2019-07-26 [1] RSPM (R 4.0.2)
#>  knitr         1.30       2020-09-22 [1] RSPM (R 4.0.2)
#>  lattice       0.20-41    2020-04-02 [2] CRAN (R 4.0.2)
#>  lava          1.6.8      2020-09-26 [1] RSPM (R 4.0.2)
#>  lhs           1.1.1      2020-10-05 [1] RSPM (R 4.0.2)
#>  lifecycle     0.2.0      2020-03-06 [1] RSPM (R 4.0.2)
#>  lubridate     1.7.9      2020-06-08 [1] RSPM (R 4.0.2)
#>  magrittr      1.5        2014-11-22 [1] RSPM (R 4.0.2)
#>  MASS          7.3-51.6   2020-04-26 [2] CRAN (R 4.0.2)
#>  Matrix        1.2-18     2019-11-27 [2] CRAN (R 4.0.2)
#>  memoise       1.1.0      2017-04-21 [1] RSPM (R 4.0.2)
#>  munsell       0.5.0      2018-06-12 [1] RSPM (R 4.0.2)
#>  nnet          7.3-14     2020-04-26 [2] CRAN (R 4.0.2)
#>  parsnip       0.1.3      2020-08-04 [1] RSPM (R 4.0.2)
#>  pillar        1.4.6      2020-07-10 [1] RSPM (R 4.0.2)
#>  pkgbuild      1.1.0      2020-07-13 [1] RSPM (R 4.0.2)
#>  pkgconfig     2.0.3      2019-09-22 [1] RSPM (R 4.0.2)
#>  pkgload       1.1.0      2020-05-29 [1] RSPM (R 4.0.2)
#>  plyr          1.8.6      2020-03-03 [1] RSPM (R 4.0.2)
#>  prettyunits   1.1.1      2020-01-24 [1] RSPM (R 4.0.2)
#>  pROC          1.16.2     2020-03-19 [1] RSPM (R 4.0.2)
#>  processx      3.4.4      2020-09-03 [1] RSPM (R 4.0.2)
#>  prodlim       2019.11.13 2019-11-17 [1] RSPM (R 4.0.2)
#>  ps            1.3.4      2020-08-11 [1] RSPM (R 4.0.2)
#>  purrr         0.3.4      2020-04-17 [1] RSPM (R 4.0.2)
#>  R6            2.4.1      2019-11-12 [1] RSPM (R 4.0.2)
#>  Rcpp          1.0.5      2020-07-06 [1] RSPM (R 4.0.2)
#>  recipes     * 0.1.13     2020-06-23 [1] RSPM (R 4.0.2)
#>  remotes       2.2.0      2020-07-21 [1] RSPM (R 4.0.2)
#>  rlang         0.4.7      2020-07-09 [1] RSPM (R 4.0.2)
#>  rmarkdown     2.4        2020-09-30 [1] CRAN (R 4.0.2)
#>  rpart         4.1-15     2019-04-12 [2] CRAN (R 4.0.2)
#>  rprojroot     1.3-2      2018-01-03 [1] RSPM (R 4.0.2)
#>  scales        1.1.1      2020-05-11 [1] RSPM (R 4.0.2)
#>  sessioninfo   1.1.1      2018-11-05 [1] RSPM (R 4.0.2)
#>  stringi       1.5.3      2020-09-09 [1] RSPM (R 4.0.2)
#>  stringr       1.4.0      2019-02-10 [1] RSPM (R 4.0.2)
#>  survival      3.1-12     2020-04-10 [2] CRAN (R 4.0.2)
#>  testthat      2.3.2      2020-03-02 [1] RSPM (R 4.0.2)
#>  tibble        3.0.3      2020-07-10 [1] RSPM (R 4.0.2)
#>  tidyr         1.1.2      2020-08-27 [1] RSPM (R 4.0.2)
#>  tidyselect    1.1.0      2020-05-11 [1] RSPM (R 4.0.2)
#>  timeDate      3043.102   2018-02-21 [1] RSPM (R 4.0.2)
#>  tune          0.1.1      2020-07-08 [1] RSPM (R 4.0.2)
#>  usemodels     0.0.1      2020-09-22 [1] RSPM (R 4.0.2)
#>  usethis       1.6.3      2020-09-17 [1] RSPM (R 4.0.2)
#>  vctrs         0.3.4      2020-08-29 [1] RSPM (R 4.0.2)
#>  withr         2.3.0      2020-09-22 [1] RSPM (R 4.0.2)
#>  workflows     0.2.1      2020-10-08 [1] RSPM (R 4.0.2)
#>  xfun          0.18       2020-09-29 [1] CRAN (R 4.0.2)
#>  yaml          2.2.1      2020-02-01 [1] RSPM (R 4.0.2)
#>  yardstick     0.0.7      2020-07-13 [1] RSPM (R 4.0.2)
#> 
#> [1] /home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0
#> [2] /opt/R/4.0.2/lib/R/library
```

<sup>Created on 2020-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by juliasilge**
This PR closes #7 by unquoting/splicing the character vector into `one_of()`.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(recipes)
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

usemodels::use_glmnet(cty ~ ., data = mpg)
#> glmnet_recipe <- 
#>   recipe(formula = cty ~ ., data = mpg) %>% 
#>   step_string2factor(one_of("manufacturer", "model", "trans", "drv", "fl", "class")) %>% 
#>   step_novel(all_nominal(), -all_outcomes()) %>% 
#>   step_dummy(all_nominal(), -all_outcomes()) %>% 
#>   step_zv(all_predictors()) %>% 
#>   step_normalize(all_predictors(), -all_nominal()) 
#> 
#> glmnet_spec <- 
#>   linear_reg(penalty = tune(), mixture = tune()) %>% 
#>   set_mode("regression") %>% 
#>   set_engine("glmnet") 
#> 
#> glmnet_workflow <- 
#>   workflow() %>% 
#>   add_recipe(glmnet_recipe) %>% 
#>   add_model(glmnet_spec) 
#> 
#> glmnet_grid <- tidyr::crossing(penalty = 10^seq(-6, -1, length.out = 20), mixture = c(0.05, 
#>     0.2, 0.4, 0.6, 0.8, 1)) 
#> 
#> glmnet_tune <- 
#>   tune_grid(glmnet_workflow, resamples = stop("add your rsample object"), grid = glmnet_grid)

glmnet_recipe <- 
  recipe(formula = cty ~ ., data = mpg) %>% 
  step_string2factor(one_of("manufacturer", "model", "trans", "drv", "fl", "class")) %>% 
  step_novel(all_nominal(), -all_outcomes()) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors(), -all_nominal()) 

prep(glmnet_recipe, mpg) %>% juice()
#> # A tibble: 234 x 77
#>     displ   year     cyl   hwy   cty manufacturer_ch… manufacturer_do…
#>     <dbl>  <dbl>   <dbl> <dbl> <int>            <dbl>            <dbl>
#>  1 -1.29  -0.998 -1.17   0.934    18           -0.297           -0.432
#>  2 -1.29  -0.998 -1.17   0.934    21           -0.297           -0.432
#>  3 -1.14   0.998 -1.17   1.27     20           -0.297           -0.432
#>  4 -1.14   0.998 -1.17   1.10     21           -0.297           -0.432
#>  5 -0.520 -0.998  0.0689 0.430    16           -0.297           -0.432
#>  6 -0.520 -0.998  0.0689 0.430    18           -0.297           -0.432
#>  7 -0.288  0.998  0.0689 0.598    18           -0.297           -0.432
#>  8 -1.29  -0.998 -1.17   0.430    18           -0.297           -0.432
#>  9 -1.29  -0.998 -1.17   0.262    16           -0.297           -0.432
#> 10 -1.14   0.998 -1.17   0.766    20           -0.297           -0.432
#> # … with 224 more rows, and 70 more variables: manufacturer_ford <dbl>,
#> #   manufacturer_honda <dbl>, manufacturer_hyundai <dbl>,
#> #   manufacturer_jeep <dbl>, manufacturer_land.rover <dbl>,
#> #   manufacturer_lincoln <dbl>, manufacturer_mercury <dbl>,
#> #   manufacturer_nissan <dbl>, manufacturer_pontiac <dbl>,
#> #   manufacturer_subaru <dbl>, manufacturer_toyota <dbl>,
#> #   manufacturer_volkswagen <dbl>, model_a4 <dbl>, model_a4.quattro <dbl>,
#> #   model_a6.quattro <dbl>, model_altima <dbl>, model_c1500.suburban.2wd <dbl>,
#> #   model_camry <dbl>, model_camry.solara <dbl>, model_caravan.2wd <dbl>,
#> #   model_civic <dbl>, model_corolla <dbl>, model_corvette <dbl>,
#> #   model_dakota.pickup.4wd <dbl>, model_durango.4wd <dbl>,
#> #   model_expedition.2wd <dbl>, model_explorer.4wd <dbl>,
#> #   model_f150.pickup.4wd <dbl>, model_forester.awd <dbl>,
#> #   model_grand.cherokee.4wd <dbl>, model_grand.prix <dbl>, model_gti <dbl>,
#> #   model_impreza.awd <dbl>, model_jetta <dbl>, model_k1500.tahoe.4wd <dbl>,
#> #   model_land.cruiser.wagon.4wd <dbl>, model_malibu <dbl>, model_maxima <dbl>,
#> #   model_mountaineer.4wd <dbl>, model_mustang <dbl>,
#> #   model_navigator.2wd <dbl>, model_new.beetle <dbl>, model_passat <dbl>,
#> #   model_pathfinder.4wd <dbl>, model_ram.1500.pickup.4wd <dbl>,
#> #   model_range.rover <dbl>, model_sonata <dbl>, model_tiburon <dbl>,
#> #   model_toyota.tacoma.4wd <dbl>, trans_auto.l3. <dbl>, trans_auto.l4. <dbl>,
#> #   trans_auto.l5. <dbl>, trans_auto.l6. <dbl>, trans_auto.s4. <dbl>,
#> #   trans_auto.s5. <dbl>, trans_auto.s6. <dbl>, trans_manual.m5. <dbl>,
#> #   trans_manual.m6. <dbl>, drv_f <dbl>, drv_r <dbl>, fl_d <dbl>, fl_e <dbl>,
#> #   fl_p <dbl>, fl_r <dbl>, class_compact <dbl>, class_midsize <dbl>,
#> #   class_minivan <dbl>, class_pickup <dbl>, class_subcompact <dbl>,
#> #   class_suv <dbl>
```

<sup>Created on 2020-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

### CODE REVIEW

**Comment by juliasilge** [comment]
I looked around and I don't think there are any similar problems for the other template pieces.

File: R/misc.R [hunk 1]
```diff
@@ -107,7 +107,6 @@ factor_check <- function(base, rec, add, colors = TRUE) {
     purrr::map_lgl(rec$template %>% dplyr::select(dplyr::one_of(nominal)),
                    rlang::is_character)
   if (any(is_str)) {
-    nominal <- rlang::syms(nominal[is_str])
```
Comment (DavisVaughan) [inline R/misc.R:110]: Do you still need to do the `is_str` subset? so `nominal <- nominal[is_str]`

Comment (juliasilge) [reply R/misc.R:110]: Oh gosh 🙈 yep
